name: Build and deploy to branch
on:
  push:
    branches:
      - main
jobs:
  push-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest"
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: dist
          folder: public
